# general configuration
url: http://miwong.me
baseurl: ''

# compass configuration
compass:
  # an avatar or logo (optional)
  logo: "/images/profile.jpg"

  # author will appear under the avatar (optional)
  author: "Michelle Wong"

  # tagline will appear under the title (optional)
  tagline: "PhD student in computer security"

  # if include_about is true, the contents of the about.html include will be
  # added under the tagline, if present.
  include_about: true

  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true

  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: true

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty
#relative_permalinks: true
